package servlet;

import da.ContactUs;
import domain.Contact;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.*;
import java.io.IOException;
import java.sql.Timestamp;
import java.util.Date;

@WebServlet(name = "SubmitContact", urlPatterns = {"/SubmitContact"})
public class ContactUs_Customer extends HttpServlet {

    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        String name = request.getParameter("name");
        String email = request.getParameter("email");
        String phoneNumber = request.getParameter("phoneNumber");
        String description = request.getParameter("description");

        if (name != null && email != null && phoneNumber != null && description != null) {
            try {
                // Get the ContactUs DAO to generate the next ID
                ContactUs db = new ContactUs();
                
                // Creating the Contact object with all required fields
                // For new contact submissions, we'll set default values for some fields
                Contact contact = new Contact(
                    null,  // contactusId will be generated by the DAO
                    name,
                    phoneNumber,
                    email,
                    description,
                    "Pending",  // Default status for new submissions
                    null,       // No staff assigned yet
                    null,       // No manager assigned yet
                    new Timestamp(new Date().getTime())  // Current timestamp
                );

                // Insert the contact record
                db.insertRecord(contact);

                request.setAttribute("message", "Message submitted successfully!");
            } catch (Exception e) {
                e.printStackTrace();
                request.setAttribute("message", "Error: " + e.getMessage());
            }
        }

        // Forward back to the contact page with a message
        request.getRequestDispatcher("contactus_customer.jsp").forward(request, response);
    }
}

